name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**"
  schedule:
    - cron: '0 1 * * *'
  # Able to call by other workflow
  workflow_call:
  # Able to call on GitHub
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  markdown_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          config: '.markdownlint.yaml'
          globs: '**/README.md'

  python_lint_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v2
