name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

concurrency:
  group: "release-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  tag_release_artifacts:
    # This only runs if this workflow is initiated via a tag-push with pattern 'v*'
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    name: collect v-tag release artifacts
    runs-on: ubuntu-latest
    needs:
      - ci
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: 'Create Release'
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            README.md
          token: ${{ secrets.GITHUB_TOKEN }}
